version: "3.3"

services:
  db:
    container_name: sistemas_gestao_db_dev
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: