# Generated by Django 4.0.4 on 2022-05-14 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nota_corte', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('quantidade_grupos', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('periodo', models.CharField(max_length=6)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_turma',
            },
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_turmaaluno',
            },
        ),
    ]
