# Generated by Django 4.0.4 on 2022-05-14 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_grupo',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('disponivel', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('consolidado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_projeto',
            },
        ),
        migrations.CreateModel(
            name='ProjetoGrupo',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_selecao_projeto', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Projetos Grupos',
                'db_table': 'tb_projeto_grupo',
                'ordering': ['data_selecao_projeto'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
                ('prazo', models.DateTimeField()),
                ('situacao', models.CharField(max_length=10)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.projeto')),
            ],
        ),
    ]
