# Generated by Django 4.0.4 on 2022-05-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('projetos', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='responsavel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='projetogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.grupo'),
        ),
        migrations.AddField(
            model_name='projetogrupo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turmas.disciplina'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='grupo',
            field=models.ManyToManyField(blank=True, through='projetos.ProjetoGrupo', to='projetos.grupo'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.professor'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turmas.disciplina'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='lider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lideres', related_query_name='lider', to='usuarios.aluno'),
        ),
    ]
