# Generated by Django 4.0.4 on 2022-05-15 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_tarefa_table_grupotarefa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='prazo',
            new_name='hora',
        ),
        migrations.AddField(
            model_name='grupotarefa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
