# Generated by Django 4.0.4 on 2022-05-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_rename_prazo_tarefa_hora_tarefa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
